# Site
title:              Karynne Bayer - Psicologia Clínica 
bio:                'Olá, bem vindo ao Espaço Terapêutico Karynne Bayer. Agende sua consulta através do número (21) 99893-4111 ou por WhatsApp. Siga-me também nas redes sociais. Aguardo seu contato.' # Colocar aqui uma breve biografia.
description:        "Psicóloga pela Universidade Federal Fluminense, 
                    Mestre em Psicologia Social, do Trabalho e das Organizações pela Universidade de Brasília. " # Colocar aqui uma breve descrição.
reading_time:       true
words_per_minute:   300
logo:               'assets/img/logo-lilas.jpg'
#background:         'assets/img/placeholder-big.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Defina isso como 'true' se você quiser colocar sua imagem de plano de fundo em branco. Caso contrário, ela será coberta.
locale:             pt_BR

# Desenvolvimento
#url:               http://localhost:4000  # URL Local para desenvolvimento.
#projectname:        ''

#Produção
url:                https://luizfragabr.github.io/karynne_bayer # URL de produção.
projectname:        'karynne_bayer'

foto_rosto:         '/assets/img/foto_karynne_bayer_fab.jpg'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   luizfragabr

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
instagram:          psicologia_karynnebayer
linkedin:           karynne-bayer-5202b46a
facebook:           Karynne-Bayer
#twitter:            username
#medium:            '@username'
#github-url:         username
#youtube:           username
#youtube-channel:   channel
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#xing:              username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
