# Site
title:              PSICÓLOGA KARYNNE BAYER 
boas_vindas:        'Bem-vindo a este espaço terapêutico!'
citacao:            '”O meu resultado é a sua saúde emocional e o seu bem-estar de volta!”'
forma_atendimento:  'Atendimentos on-line e presencial'
agendamento:        'Agende sua consulta pelo número (21) 99893-4111 ou por WhatsApp'
redes_sociais:      'Siga-me também nas redes sociais.'
description:        "Focada no tratamento da ansiedade, depressão, e adoecimentos relacionados à saúde emocional no trabalho." # Colocar aqui uma breve descrição.
reading_time:       true
words_per_minute:   200
logo_interno:       'assets/img/logo-verde.jpg'
logo_principal:     'assets/img/content/foto_rosto.jpg'
#background:        'assets/img/placeholder-big.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # true = Usa a imagem de fundo tamanho normal; false = tamanho extendido.
locale:             pt_BR
foto_rosto:         '/assets/img/foto_karynne_bayer_fab.jpg'
baseurl:            '' # subcaminho para o site, exemplo: /blog
url:               https://karynnebayer.netlify.com # URL de produção.


# Jekyll
permalink:          /:title/  # URLs amigáveis.
markdown:           kramdown  # Tipo de parser MD utilizado.
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   karynne-bayer

# Social
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
mobile:             (21) 99893-4111
email_dev:          luizfragabr@yahoo.com.br 
email:              kbayer.psicologia@gmail.com
instagram:          psicologia_karynnebayer
#linkedin:           karynne-bayer-5202b46a
facebook:           Karynne-Bayer
#twitter:            username
#medium:            '@username'
#github-url:         username
#youtube:           username
#youtube-channel:   channel
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#xing:              username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
